name: video_editor_pro
description: Video Editor Pro
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.0
  image_picker: ^1.0.7
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  google_fonts: ^6.1.0
  permission_handler: ^11.3.1
flutter:
  uses-material-design: true
